### ISSUE TITLE
If collation is utf8_unicode_502_ci the plugin does not see it and it is not downgraded

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/databasecollationfix#1]
Importing a site containing utf8_unicode_502_ci does not get converted to utf8mb4_unicode_ci Collation
Also if you use the "Collation Fix" under tools it does not see anything to correct

![screen shot 2017-02-24 at 8 20 59 am](https://cloud.githubusercontent.com/assets/1041421/23311423/f3c448d4-fa6a-11e6-9ff6-f4ebd6049472.png)

**Comment by davejesch** [comment]
Are you referring to utf8_unicode_502_ci or utf8_unicode_520_ci? The code is now checking for utf8_unicode_520_ci and updating those. I don't think there is a utf8_unicode_502_ci Collation Algorithm. Please verify.

**Comment by GreggFranklin** [comment]
Works correctly!
