### ISSUE TITLE
DS 5 and the Activate Collation Fix

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/databasecollationfix#10]
#### STEPS TO REPRODUCE: 
1. Install DS 5
2. Activate Database Collation Fix

#### RESULTS: 
Notice: Undefined property:
DS_Runtime::$last_ui_event in C:\ProgramData\.ds\plugins\databasecollationfix\prepend.php on line 17
Notice: Undefined property: DS_Runtime::$last_ui_event in C:\ProgramData\.ds\plugins\databasecollationfix\prepend.php on line 19
Notice: Trying to get property 'action' of non-object in C:\ProgramData\.ds\plugins\databasecollationfix\prepend.php on line 19

#### EXPECTED RESULT:
No Errors

Operating System:  Windows 10

**Comment by davejesch** [comment]
Steve added a fix for DS5 compatability

**Comment by MarcBenzakein** [comment]
Tested on both DS 3.x and DS5 on 10/7/2021. Fixed.
