### ISSUE TITLE
After pushing the Collision Fix button under tools it reports no Altered tables and columns

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/databasecollationfix#2]
User visits the sites Dashboard > Tools > Collation Fix 
Clicks the [ Fix Database Collation ] 
Presented with a results and indicates nothing was done
However database reflects that the changes where made
![screen shot 2017-05-10 at 9 51 37 pm](https://cloud.githubusercontent.com/assets/1041421/25933467/c8e8bfcc-35cb-11e7-92e8-33e5ebd7e9cc.jpg)

**Comment by davejesch** [comment]
What changes were made to the database? Do you have a before/after export of the database that I can see? The database changes often; I just need to verify if any of the collation settings have changed when the report is indicating no changes.

**Comment by GreggFranklin** [comment]
This issue appears to have been resolved with other fixes.
