### ISSUE TITLE
Add a select UI to pick collation type

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/databasecollationfix#3]
Adding an ability to pick the collation type could be quite handy.

![screen shot 2017-05-10 at 10 23 43 pm](https://cloud.githubusercontent.com/assets/1041421/25934060/8a107830-35d0-11e7-9822-7d377c60f8ac.jpg)

**Comment by davejesch** [comment]
implemented here https://github.com/ServerPress/databasecollationfix/commit/dc324506f82439bf6d34dc9854df3a56b3d39cb6

**Comment by GreggFranklin** [comment]
Dave had mention adding other collation types. But the current UI and set of collation works great - closing
