### ISSUE TITLE
Composer'ize repo

### ISSUE THREAD

**Issue by Steveorevo** [ServerPress/databasecollationfix#4]
Please include a base composer.json with the type: wordpress-plugin (see admin-color-bar for example). This will allow for automated builds, updates, and future conflict resolution tool. Lastly, please provide third version point in version naming schema: i.e. next release would be 1.0.1, etc.

**Comment by davejesch** [comment]
added composer file https://github.com/ServerPress/databasecollationfix/commit/4a2450c312072b7ed1683a2d613628318573a96c

**Comment by GreggFranklin** [comment]
Looks good!
