### ISSUE TITLE
During WP install, plugin displays "Error establishing database connection" message

### ISSUE THREAD

**Issue by davejesch** [ServerPress/databasecollationfix#5]
STEPS TO REPRODUCE:
1. Activate DCF via DS plugins
2. create a new site
3. Go to install screen on new site.

RESULTS:
Displays the "Error establishing database connection" message when going to the wp-admin/install.php page

EXPECTED RESULTS:
no error message

Looks like DCF is trying to read information from the db before WP has bootstrapped that part of itself.

Only happens within DS.

**Comment by davejesch** [comment]
fixed with commit https://github.com/ServerPress/databasecollationfix/commit/607bdd6df91a602b74ac30fe0d859fefc5658bac

**Comment by GreggFranklin** [comment]
Issue resolved - closing
