### ISSUE TITLE
Issuing a WP-CLI command when Clean-import and DS-CLI are active produce the wp-config.php file output

### ISSUE THREAD

**Issue by davejesch** [ServerPress/databasecollationfix#6]
@GreggFranklin commented on [Thu May 10 2018](https://github.com/ServerPress/clean-import/issues/19)

#### STEPS TO REPRODUCE: 
1. Activate Clean Import and DS-CLI
2. Visit any sites DS-CLI > Terminal
3. At the Prompt type: WP

#### RESULTS: 
Outputs the wp-config.php file

#### EXPECTED RESULT:
Should output WP-CLI's WP Description, Synopsis and Subcommands

**Comment by GreggFranklin** [comment]
Issue Resolved
