### ISSUE TITLE
_520 Collation error when deploying site even though the Database Collation Fix plugin is active

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/databasecollationfix#7]
Received an import that contained a database with utf8mb4_unicode_520_ci still in tact even after the DB Collation Fix plugin repaired all other instances. 

DROP TABLE IF EXISTS `wp_pmxi_history`;
/*!40101 SET @saved_cs_client     = @@character_set_client */;
/*!40101 SET character_set_client = utf8 */;
CREATE TABLE `wp_pmxi_history` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `import_id` bigint(20) unsigned NOT NULL,
  `type` enum('manual','processing','trigger','continue','') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_520_ci NOT NULL DEFAULT '',
  `time_run` text COLLATE utf8mb4_unicode_ci,
  `date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `summary` text COLLATE utf8mb4_unicode_ci,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
/*!40101 SET character_set_client = @saved_cs_client */;

**Comment by davejesch** [comment]
Fixed. To test, import the customer's database again. Use phpMyAdmin to verify that the 'type' column's collation algorithm is 'utf8mb4_unicode_520_ci'. Then go to Tools -&gt; Collation Fix in admin and click on the "Fix Database Collation" button. You'll see a report of what was updated in the database and then look for the wp_pmxi_history' table's 'type' column. You'll see that it was updated. Then verify the columns collation algorithm via phpMyAdmin as well.
