### ISSUE TITLE
Full text index causing column alterations to fail

### ISSUE THREAD

**Issue by davejesch** [ServerPress/databasecollationfix#8]
#### STEPS TO REPRODUCE: 
1. CREATE TABLE wp_connections(
 id bigint(20) NOT NULL AUTO_INCREMENT,
 ts timestamp NULL DEFAULT NULL,
 date_added tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 ordo int(11) NOT NULL DEFAULT '0',
 entry_type tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 visibility tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 slug tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 family_name tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 honorific_prefix tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 first_name tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 middle_name tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 last_name tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 honorific_suffix tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 titletiny text COLLATE utf8mb4_unicode_520_ci NOT NULL,
 organization tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 department tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 contact_first_name longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 contact_last_name longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 social longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 links longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 dates longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 birthday tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 anniversary tinytext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 bio longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 notes longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 excerpt text COLLATE utf8mb4_unicode_520_ci NOT NULL,
 options longtext COLLATE utf8mb4_unicode_520_ci NOT NULL,
 added_by bigint(20) NOT NULL,
 edited_by bigint(20) NOT NULL,
 owner bigint(20) NOT NULL,
 user bigint(20) NOT NULL,
 status varchar(20) COLLATE utf8mb4_unicode_520_ci NOT NULL,
 PRIMARY KEY (id),
 FULLTEXT KEY search (last_name,organization,department,contact_first_name,contact_last_name,notes)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;
2. Click the "Fix Collation Button"

#### RESULTS: 
ALTER TABLE statements fail on any column listed in the FULLTEXT KEY SEARCH clause

#### EXPECTED RESULT:
No errors; column collation updated

Reported by https://secure.helpscout.net/conversation/619172225/201919?folderId=88236

**Comment by davejesch** [comment]
added code to remove, then recreate any FULLTEXT indexes found for a table; updated report to include count of INDEXes modified.

Still waiting for word back from the customer to see if these changes have fixed their problem but local testing shows that it's working well.

**Comment by erinmarinas** [comment]
Issue resolved
