### ISSUE TITLE
The settings page shows results along with a lot of code. 

### ISSUE THREAD

**Issue by GreggFranklin** [ServerPress/databasecollationfix#9]
#### STEPS TO REPRODUCE: 
1. Go to the Dashboard > Tool  > Collation FIxx
2.  Check the box for Force Collation Algorithm to:
3.  Click the [ Fix Database Collation ]

#### RESULTS: 
![image 7](https://user-images.githubusercontent.com/1041421/44437225-ed890b80-a56d-11e8-899d-9bc7141d77bc.jpg)

#### EXPECTED RESULT:
Not so verbose

DesktopServer Version: 3.9.2 Beta 1
Operating System:  Windows 10

**Comment by davejesch** [comment]
This is not new behavior- it's always done this to indicate what tables and columns are being updated. We can simplify the output to be less "techy" rather than the SQL statements that are being executed. You'r "Expected Result" of "Not so verbose" need to be expanded. Examples please? :)

**Comment by GreggFranklin** [comment]
Maybe:

**Forcing Collation Alogrithm to: utf8mb4_unicode_ci.**

Changing Collation Algorithm to: utf8mb4_unicode_ci
ALTER DATABASE 'latestDBrj2m7' COLLATE=utf8mb4_unicode_ci
Checking table "wp_commentmeta"...
Create table "wp_commentmeta"...
Searching FULLTEXT INDEX: false
Checking table "wp_comments"...
Create table "wp_comments"...
no ALTERaionts required.
Checking table "wp_links"...
Create table "wp_links"...
no ALTERaionts required.

**Comment by GreggFranklin** [comment]
Going to close this ticket as we are seeing less use of this plugin.
